# Generated by Django 4.1.2 on 2022-10-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_alter_user_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(max_length=30)),
                ('course_name', models.CharField(max_length=100)),
                ('time_duration', models.TimeField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('phn_number', models.IntegerField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
    ]
