# Generated by Django 4.1.2 on 2022-10-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_certificate_contact_course_profile_quiz_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='profile_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
