# Generated by Django 4.1.2 on 2022-12-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_certificate_contact_course_profile_quiz_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phn_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
    ]
