# Generated by Django 4.1.2 on 2022-12-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_gender_profile_phn_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
