# Generated by Django 4.1.2 on 2022-12-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_certificate_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
