# Generated by Django 4.1.2 on 2022-12-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_certificate_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
