# Generated by Django 4.1.2 on 2022-12-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_contact_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_email',
        ),
    ]
