# Generated by Django 4.1.2 on 2022-12-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_certificate_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
