# Generated by Django 4.1.2 on 2022-12-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_certificate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
