# Generated by Django 4.1.2 on 2022-12-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_certificate_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='', null=True, upload_to='profile'),
        ),
    ]
