# Generated by Django 4.1.2 on 2022-12-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_certificate_user_id_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
