# Generated by Django 4.1.2 on 2022-12-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
