# Generated by Django 4.1.2 on 2022-12-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_certificate_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
