# Generated by Django 4.1.2 on 2022-12-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_contact_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
