# Generated by Django 4.1.2 on 2022-12-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
