# Generated by Django 4.1.2 on 2022-12-13 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_payment_profile_id_payment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.user'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
