# Generated by Django 4.1.2 on 2022-12-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_certificate_course_alter_certificate_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
