# Generated by Django 4.1.2 on 2022-12-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='uniq_id',
        ),
    ]
