# Generated by Django 4.1.2 on 2022-12-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.CharField(max_length=20),
        ),
    ]
