# Generated by Django 4.1.2 on 2022-12-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_course_time_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
