# Generated by Django 4.1.2 on 2022-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
