# Generated by Django 4.1.2 on 2022-12-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='name',
        ),
    ]
