# Generated by Django 4.1.2 on 2022-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_rename_user_name_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True),
        ),
    ]
