# Generated by Django 4.1.2 on 2022-12-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uniq_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ManyToManyField(to='home.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
