# Generated by Django 4.1.2 on 2022-12-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_rename_uniq_id_user_id_remove_quiz_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
